# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/CA_CEP_copy.cache/wt} [current_project]
set_property parent.project_path {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/CA_CEP_copy.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/CA_CEP_copy.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/Header.svh}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/UART/Header.svh}
}
set_property file_type "Verilog Header" [get_files {{C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/Header.svh}}]
set_property file_type "Verilog Header" [get_files {{C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/UART/Header.svh}}]
read_verilog -library xil_defaultlib -sv {
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/ALU.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/BranchCond.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/CSR_Reg_file.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/UART/Comparator_3bit.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/UART/Comparator_4bit.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/ControlPath.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/Counter.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/UART/D_FlipFlop.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/DataPath.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/Data_Mem.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/Decode.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/Decode_Execute.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/UART/DownClocking_BaudRate.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/UART/DownCounter_1bit.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/UART/Edge_to_Pulse.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/Execute.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/FF_1bit.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/FF_32bit.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/Fetch.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/Full_Forwarding_Unit.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/ImmGen.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/Instr_Mem.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/Load_Store_Unit.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/MUX2x1.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/UART/MUX2x1_1bit.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/UART/MUX2x1_4bit.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/MUX3x1.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/MUX4x1.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/Memory.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/Memory_Writeback.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/Reg_file.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/UART/Reloadable_DownCounter.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/UART/ShiftReg_10bit_Rx.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/UART/ShiftReg_10bit_Tx.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/UART/StateMachine.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/UART/UART.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/UART/UART_Controller.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/UART/UART_Datapath.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/Writeback.sv}
  {C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/Pipelined_Processor.sv}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/CA_CEP_copy.srcs/constrs_2/new/UART_CEP.xdc}}
set_property used_in_implementation false [get_files {{C:/DriveA/Workspaces/Vivado/CA_Lab/CEP - Copy/CA_CEP_copy.srcs/constrs_2/new/UART_CEP.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Pipelined_Processor -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Pipelined_Processor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Pipelined_Processor_utilization_synth.rpt -pb Pipelined_Processor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
