# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/CA_CEP.cache/wt [current_project]
set_property parent.project_path C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/CA_CEP.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/DriveA/Workspaces/Vivado/CA_Lab/CEP/CA_CEP.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/Header.svh
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/UART/Header.svh
}
set_property file_type "Verilog Header" [get_files C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/Header.svh]
set_property file_type "Verilog Header" [get_files C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/UART/Header.svh]
read_verilog -library xil_defaultlib -sv {
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/ALU.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/BranchCond.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/CSR_Reg_file.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/UART/Comparator_3bit.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/UART/Comparator_4bit.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/ControlPath.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/Counter.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/UART/D_FlipFlop.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/DataPath.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/Data_Mem.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/Decode.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/Decode_Execute.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/UART/DownClocking_BaudRate.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/UART/DownCounter_1bit.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/Execute.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/FF_32bit.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/Fetch.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/Full_Forwarding_Unit.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/ImmGen.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/Instr_Mem.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/Load_Store_Unit.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/MUX2x1.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/UART/MUX2x1_1bit.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/MUX3x1.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/MUX4x1.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/Memory.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/Memory_Writeback.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/Reg_file.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/UART/Reloadable_DownCounter.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/UART/ShiftReg_10bit_Rx.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/UART/ShiftReg_10bit_Tx.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/UART/StateMachine.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/UART/UART.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/UART/UART_Controller.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/UART/UART_Datapath.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/Writeback.sv
  C:/DriveA/Workspaces/Vivado/CA_Lab/CEP/Pipelined_Processor.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Pipelined_Processor -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Pipelined_Processor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Pipelined_Processor_utilization_synth.rpt -pb Pipelined_Processor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
